use_frameworks!

target 'DZ_UIKit_Example', :exclusive => true do
  pod 'DZ_UIKit', :path => '../'
end

target 'DZ_UIKit_Tests', :exclusive => true do
  pod 'DZ_UIKit', :path => '../'

  pod 'FBSnapshotTestCase'
end
